### ISSUE TITLE
Nav bar is huge in firefox browser.

### ISSUE THREAD

**Issue by sebohe** [aragon/aragon-ui#222] opened 2018-10-16 18:25 UTC
Nav Bar is huge in firefox-developer-edition. This nav bar inherits is from AppBar aragon-ui component.

```
import { AragonApp, AppBar, observe, Text } from '@aragon/ui'
const AltheaAppBar = styled(AppBar)`
    background: #efefef;
    border: 2px solid #ddd;
    border-radius: 5px;
    padding: 0;
    margin: 20px 0;
    height: 100%;
  `
```

Firefox:
![aragon-banner](https://user-images.githubusercontent.com/10123236/47037919-0d374d00-d135-11e8-802a-89c4905fc4fe.png)

Chromium
![chrome](https://user-images.githubusercontent.com/10123236/47038125-8f277600-d135-11e8-8c40-c2f54d7e5116.png)

**Comment by bpierre** [comment] 2018-10-16 21:06
@sebohe It looks like it is caused by `height: 100%`? If not, could you try to isolate the issue on https://codesandbox.io/ ?

Also you might not need `AppBar` at all, since you are using a custom style and navigation.

**Comment by bpierre** [comment] 2018-10-29 11:34
@sebohe Closing this issue, feel free to reopen if needed!

**Closed by bpierre** 2018-10-29 11:34 UTC
