### ISSUE TITLE
Remove the theme.accent color when DropDown item is selected

### ISSUE THREAD

**Issue by stellarmagnet** [aragon/aragon-ui#634] opened 2019-10-23 12:27 UTC
Here is how a panel looks that has a combination of inputs and dropdowns. Since the dropdown has a border that is conditionally colored based on if an item is selected, it looks inconsistent in comparison to traditional input fields. I would get rid of the accent color.

![image](https://user-images.githubusercontent.com/2584493/67392566-10171a00-f5a1-11e9-8bc1-0b2dbb9a1895.png)

**Comment by sohkai** [comment] 2019-10-23 14:35
Yes! This is definitely something on the to-do list (we may have put it in another issue that was closed previously).

**Comment by sohkai** [comment] 2020-01-02 18:38
Duplicate of https://github.com/aragon/aragon-ui/issues/443.

**Closed by sohkai** 2020-01-02 18:38 UTC
Labels: enhancement, good first issue
